# Tests

## Transformer

In [79]:
import tensorflow as tf
import tensorflow_datasets
from transformers import *

In [80]:
# Load dataset, tokenizer, model from pretrained model/vocabulary
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')
model = TFBertForSequenceClassification.from_pretrained('bert-base-cased')

In [ ]:
data = tensorflow_datasets.load('glue/mrpc')

In [37]:
data

{'test': <DatasetV1Adapter shapes: {idx: (), label: (), sentence1: (), sentence2: ()}, types: {idx: tf.int32, label: tf.int64, sentence1: tf.string, sentence2: tf.string}>,
 'train': <DatasetV1Adapter shapes: {idx: (), label: (), sentence1: (), sentence2: ()}, types: {idx: tf.int32, label: tf.int64, sentence1: tf.string, sentence2: tf.string}>,
 'validation': <DatasetV1Adapter shapes: {idx: (), label: (), sentence1: (), sentence2: ()}, types: {idx: tf.int32, label: tf.int64, sentence1: tf.string, sentence2: tf.string}>}

In [38]:
data.keys()

dict_keys(['test', 'train', 'validation'])

In [39]:
data['train']

<DatasetV1Adapter shapes: {idx: (), label: (), sentence1: (), sentence2: ()}, types: {idx: tf.int32, label: tf.int64, sentence1: tf.string, sentence2: tf.string}>

In [40]:
from tensorflow.python.data.ops import dataset_ops
dataset_ops.get_legacy_output_shapes(data['train'])

{'idx': TensorShape([]),
 'label': TensorShape([]),
 'sentence1': TensorShape([]),
 'sentence2': TensorShape([])}

In [41]:
dataset_ops.get_legacy_output_types(data['train'])

{'idx': tf.int32,
 'label': tf.int64,
 'sentence1': tf.string,
 'sentence2': tf.string}

In [43]:
dataset_ops.get_legacy_output_classes(data['train'])

{'idx': tensorflow.python.framework.ops.Tensor,
 'label': tensorflow.python.framework.ops.Tensor,
 'sentence1': tensorflow.python.framework.ops.Tensor,
 'sentence2': tensorflow.python.framework.ops.Tensor}

In [11]:
for l in data['train']:
    print(l.keys())
    print(l)
    print(l['idx'])
    print(l['label'])
    print(l['sentence1'])
    break

dict_keys(['idx', 'label', 'sentence1', 'sentence2'])
{'idx': <tf.Tensor: shape=(), dtype=int32, numpy=1680>, 'label': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'sentence1': <tf.Tensor: shape=(), dtype=string, numpy=b'The identical rovers will act as robotic geologists , searching for evidence of past water .'>, 'sentence2': <tf.Tensor: shape=(), dtype=string, numpy=b'The rovers act as robotic geologists , moving on six wheels .'>}
tf.Tensor(1680, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(b'The identical rovers will act as robotic geologists , searching for evidence of past water .', shape=(), dtype=string)


In [44]:
# get numpy array
for element in data['train'].as_numpy_iterator(): 
    print(element) 
    break

{'idx': 1680, 'label': 0, 'sentence1': b'The identical rovers will act as robotic geologists , searching for evidence of past water .', 'sentence2': b'The rovers act as robotic geologists , moving on six wheels .'}


In [45]:
import numpy as np
np.shape(list(data['train'].as_numpy_iterator()))

(3668,)

In [46]:
len(list(data['train'].as_numpy_iterator()))

3668

In [48]:
list(data['train'].take(1).as_numpy_iterator())

[{'idx': 1680,
  'label': 0,
  'sentence1': b'The identical rovers will act as robotic geologists , searching for evidence of past water .',
  'sentence2': b'The rovers act as robotic geologists , moving on six wheels .'}]

In [49]:
# Prepare dataset for GLUE as a tf.data.Dataset instance
train_dataset = glue_convert_examples_to_features(data['train'], tokenizer, max_length=128, task='mrpc')
valid_dataset = glue_convert_examples_to_features(data['validation'], tokenizer, max_length=128, task='mrpc')
train_dataset = train_dataset.shuffle(100).batch(32).repeat(2)
valid_dataset = valid_dataset.batch(64)

In [60]:
list(train_dataset.take(1).as_numpy_iterator())[0][0].keys()

dict_keys(['input_ids', 'attention_mask', 'token_type_ids'])

In [61]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['input_ids']

array([[  101,  1258, 12421, ...,     0,     0,     0],
       [  101,  1124,  1163, ...,     0,     0,     0],
       [  101,  1573,  5567, ...,     0,     0,     0],
       ...,
       [  101,  4673,  1108, ...,     0,     0,     0],
       [  101, 10789,  2142, ...,     0,     0,     0],
       [  101, 23306,  1163, ...,     0,     0,     0]], dtype=int32)

In [62]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['input_ids'].shape

(32, 128)

In [63]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['attention_mask']

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)

In [64]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['attention_mask'].shape

(32, 128)

In [65]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['token_type_ids']

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [66]:
list(train_dataset.take(1).as_numpy_iterator())[0][0]['token_type_ids'].shape

(32, 128)

In [69]:
encoding = tokenizer.encode("This is a simple input to be tokenized")

print("Encoded string: {}".format(encoding))

Encoded string: [101, 1188, 1110, 170, 3014, 7758, 1106, 1129, 22559, 2200, 102]


In [76]:
list(data['train'].take(1).as_numpy_iterator())[0]['sentence1'].decode("utf-8") 

'The identical rovers will act as robotic geologists , searching for evidence of past water .'

In [77]:
tokenizer.encode(list(data['train'].take(1).as_numpy_iterator())[0]['sentence1'].decode("utf-8"))

[101,
 1109,
 6742,
 187,
 24985,
 1209,
 2496,
 1112,
 24628,
 25166,
 1116,
 117,
 6205,
 1111,
 2554,
 1104,
 1763,
 1447,
 119,
 102]

In [78]:
tokenizer.encode(list(data['train'].take(1).as_numpy_iterator())[0]['sentence2'].decode("utf-8"))

[101,
 1109,
 187,
 24985,
 2496,
 1112,
 24628,
 25166,
 1116,
 117,
 2232,
 1113,
 1565,
 8089,
 119,
 102]

In [17]:
# Prepare training: Compile tf.keras model with optimizer, loss and learning rate schedule
optimizer = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08, clipnorm=1.0)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

In [18]:
model.summary()

Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  108310272 
_________________________________________________________________
dropout_37 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  1538      
Total params: 108,311,810
Trainable params: 108,311,810
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Train and evaluate using tf.keras.Model.fit()
history = model.fit(train_dataset, epochs=2, steps_per_epoch=115,
                    validation_data=valid_dataset, validation_steps=7)

In [ ]:
# Load the TensorFlow model in PyTorch for inspection
model.save_pretrained('./save/')
pytorch_model = BertForSequenceClassification.from_pretrained('./save/', from_tf=True)

In [ ]:
# Quickly test a few predictions - MRPC is a paraphrasing task, let's see if our model learned the task
sentence_0 = "This research was consistent with his findings."
sentence_1 = "His findings were compatible with this research."
sentence_2 = "His findings were not compatible with this research."
inputs_1 = tokenizer.encode_plus(sentence_0, sentence_1, add_special_tokens=True, return_tensors='pt')
inputs_2 = tokenizer.encode_plus(sentence_0, sentence_2, add_special_tokens=True, return_tensors='pt')

In [ ]:
pred_1 = pytorch_model(inputs_1['input_ids'], token_type_ids=inputs_1['token_type_ids'])[0].argmax().item()
pred_2 = pytorch_model(inputs_2['input_ids'], token_type_ids=inputs_2['token_type_ids'])[0].argmax().item()

print("sentence_1 is", "a paraphrase" if pred_1 else "not a paraphrase", "of sentence_0")
print("sentence_2 is", "a paraphrase" if pred_2 else "not a paraphrase", "of sentence_0")

## TF_Config env variable

In [11]:
import os
import json
from tensorboard.plugins.hparams import api as hp

In [4]:
os.environ['TF_CONFIG']='{"cluster": {"chief": ["127.0.0.1:2222"]}, "task": {"type": "chief", "index": 0, "trial": "2", "cloud": "cxxx-ml"}, "job": {"package_uris": ["gs://xxx/tf_bert_classification_2020_05_12_141041/b0d287bd012da97a62f662b2e9df291e899c2e9705ca751a5a0f7dcaf2849765/bert_model-0.1.tar.gz"], "python_module": "model.tf_bert_classification.task", "args": ["--epochs=1", "--steps_per_epoch_train=5", "--batch_size_train=32", "--steps_per_epoch_eval=1", "--batch_size_eval=64", "--input_eval_tfrecords=gs://multilingual_text_classification/tfrecord/sst2/bert-base-multilingual-uncased/valid", "--input_train_tfrecords=gs://xxx/tfrecord/sst2/bert-base-multilingual-uncased/train", "--output_dir=gs://xxx/training_model_gcp/tf_bert_classification_2020_05_12_141041", "--pretrained_model_dir=gs://xxx/pretrained_model/bert-base-multilingual-uncased", "--verbosity_level=INFO", "--epsilon", "1.7788921050163616e-06", "--learning_rate", "0.0007763625134788308"], "hyperparameters": {"goal": "MAXIMIZE", "params": [{"parameter_name": "learning_rate", "min_value": 1e-08, "max_value": 1.0, "type": "DOUBLE", "scale_type": "UNIT_LOG_SCALE"}, {"parameter_name": "epsilon", "min_value": 1e-09, "max_value": 1.0, "type": "DOUBLE", "scale_type": "UNIT_LOG_SCALE"}], "max_trials": 3, "max_parallel_trials": 2, "hyperparameter_metric_tag": "accuracy_train", "enable_trial_early_stopping": true, "max_failed_trials": 1}, "region": "europe-west4", "runtime_version": "2.1", "run_on_raw_vm": true, "python_version": "3.7"}, "environment": "cloud"}'

In [5]:
os.environ['TF_CONFIG']

'{"cluster": {"chief": ["127.0.0.1:2222"]}, "task": {"type": "chief", "index": 0, "trial": "2", "cloud": "cxxx-ml"}, "job": {"package_uris": ["gs://xxx/tf_bert_classification_2020_05_12_141041/b0d287bd012da97a62f662b2e9df291e899c2e9705ca751a5a0f7dcaf2849765/bert_model-0.1.tar.gz"], "python_module": "model.tf_bert_classification.task", "args": ["--epochs=1", "--steps_per_epoch_train=5", "--batch_size_train=32", "--steps_per_epoch_eval=1", "--batch_size_eval=64", "--input_eval_tfrecords=gs://multilingual_text_classification/tfrecord/sst2/bert-base-multilingual-uncased/valid", "--input_train_tfrecords=gs://xxx/tfrecord/sst2/bert-base-multilingual-uncased/train", "--output_dir=gs://xxx/training_model_gcp/tf_bert_classification_2020_05_12_141041", "--pretrained_model_dir=gs://xxx/pretrained_model/bert-base-multilingual-uncased", "--verbosity_level=INFO", "--epsilon", "1.7788921050163616e-06", "--learning_rate", "0.0007763625134788308"], "hyperparameters": {"goal": "MAXIMIZE", "params": [{"p

In [8]:
json.loads(os.environ.get("TF_CONFIG", "{}")).get("job",{}) #.get("args",{})

{'package_uris': ['gs://xxx/tf_bert_classification_2020_05_12_141041/b0d287bd012da97a62f662b2e9df291e899c2e9705ca751a5a0f7dcaf2849765/bert_model-0.1.tar.gz'],
 'python_module': 'model.tf_bert_classification.task',
 'args': ['--epochs=1',
  '--steps_per_epoch_train=5',
  '--batch_size_train=32',
  '--steps_per_epoch_eval=1',
  '--batch_size_eval=64',
  '--input_eval_tfrecords=gs://multilingual_text_classification/tfrecord/sst2/bert-base-multilingual-uncased/valid',
  '--input_train_tfrecords=gs://xxx/tfrecord/sst2/bert-base-multilingual-uncased/train',
  '--output_dir=gs://xxx/training_model_gcp/tf_bert_classification_2020_05_12_141041',
  '--pretrained_model_dir=gs://xxx/pretrained_model/bert-base-multilingual-uncased',
  '--verbosity_level=INFO',
  '--epsilon',
  '1.7788921050163616e-06',
  '--learning_rate',
  '0.0007763625134788308'],
 'hyperparameters': {'goal': 'MAXIMIZE',
  'params': [{'parameter_name': 'learning_rate',
    'min_value': 1e-08,
    'max_value': 1.0,
    'type': 'D

In [9]:
params=json.loads(os.environ.get("TF_CONFIG", "{}")).get("job",{}).get("hyperparameters",{}).get("params",{})

In [12]:
list_hp=[]
for el in params:
    hp_dict=dict(el)
    if hp_dict.get('type')=='DOUBLE':
        list_hp.append(hp.HParam(hp_dict.get('parameter_name'), hp.RealInterval(hp_dict.get('min_value'), hp_dict.get('max_value'))))

print(list_hp)

[HParam(name='learning_rate', domain=RealInterval(1e-08, 1.0), display_name=None, description=None), HParam(name='epsilon', domain=RealInterval(1e-09, 1.0), display_name=None, description=None)]


## FLAGS

In [13]:
from absl import flags
import sys

In [14]:
FLAGS = flags.FLAGS

def del_all_flags(FLAGS):
    flags_dict = FLAGS._flags()    
    keys_list = [keys for keys in flags_dict]    
    for keys in keys_list:
        FLAGS.__delattr__(keys)
    
del_all_flags(flags.FLAGS)

In [15]:
flags.DEFINE_string('f', '', 'kernel') # just for jupyter notebook and avoir : "UnrecognizedFlagError: Unknown command line flag 'f'"
flags.DEFINE_float('float', 3.14, 'using floats')

In [17]:
FLAGS(sys.argv);

In [18]:
try:
    FLAGS['float2'].value
except KeyError:
    print('key doesn t exist')

key doesn t exist


## TF.summary

In [3]:
!pip install tensorflow==2.1.0

  Using cached tensorflow-2.1.0-cp37-cp37m-macosx_10_11_x86_64.whl (120.8 MB)
  Using cached tensorflow_estimator-2.1.0-py2.py3-none-any.whl (448 kB)
Processing /Users/tarrade/Library/Caches/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd/gast-0.2.2-cp37-none-any.whl
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
  Using cached tensorboard-2.1.1-py3-none-any.whl (3.8 MB)
ERROR: bert-model 0.1 requires cloud-tpu-client==0.8, which is not installed.
ERROR: bert-model 0.1 requires google-cloud-logging==1.15.0, which is not installed.
ERROR: bert-model 0.1 has requirement google-cloud-bigquery==1.24.0, but you'll have google-cloud-bigquery 1.17.1 which is incompatible.
ERROR: bert-model 0.1 has requirement pip==20.1, but you'll have pip 20.0.2 which is incompatible.
ERROR: bert-model 0.1 has requirement tensorboard==2.2.1, but you'll have tensorboard 2.1.1 which is incompatible.
ERROR: bert-mod

In [1]:
import os
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

In [4]:
strategy = tf.distribute.MirroredStrategy()

INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:CPU:0',)


In [5]:
a = tf.constant([2, 2], name="vector")

In [6]:
b = tf.constant(2.0, name="scalar")

In [7]:
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [8]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [11]:
with strategy.scope():
    writer = tf.summary.create_file_writer("mylogs")
    with writer.as_default():
        tf.summary.scalar('metric_accuracy', data=1.0, step=1)
        tf.summary.scalar('metric_accuracy_2', data=3.0, step=1)
        tf.summary.scalar('test', data=b, step=1)

In [8]:
from tensorboard.backend.event_processing import event_accumulator

In [9]:
event_acc = event_accumulator.EventAccumulator("mylogs")
event_acc.Reload()

In [10]:
event_acc.Tags()

{'images': [],
 'audio': [],
 'histograms': [],
 'scalars': [],
 'distributions': [],
 'tensors': ['metric_accuracy', 'metric_accuracy_2', 'test'],
 'graph': False,
 'meta_graph': False,
 'run_metadata': []}

In [11]:
for tag in sorted(event_acc.Tags()['tensors']):
    for scalar_event in event_acc.Tensors(tag):
        print('name: {} value: {} step: {}'.format(tag, tf.make_ndarray(scalar_event.tensor_proto), scalar_event.step))
        #print(scalar_event.step)
        #print(tf.make_ndarray(scalar_event.tensor_proto))
        

name: metric_accuracy value: 1.0 step: 1
name: metric_accuracy_2 value: 3.0 step: 1
name: test value: 2.0 step: 1


In [14]:
from tensorboard.backend.event_processing import event_accumulator
event_acc = event_accumulator.EventAccumulator('gs://'+os.environ['BUCKET_NAME']+'/training_model_gcp/tf_bert_classification_hp_tuning_cpu_2020_06_10_095311/tensorboard/trial_id_1/validation')
event_acc.Reload()
print(event_acc.Tags())

{'images': [], 'audio': [], 'histograms': [], 'scalars': ['epoch_loss', 'epoch_accuracy'], 'distributions': [], 'tensors': ['testtesttest_1'], 'graph': False, 'meta_graph': False, 'run_metadata': []}


In [15]:
from tensorboard.backend.event_processing import event_accumulator
event_acc = event_accumulator.EventAccumulator('gs://'+os.environ['BUCKET_NAME']+'/training_model_gcp/tf_bert_classification_hp_tuning_cpu_2020_06_10_095311/tensorboard/trial_id_1/validation')
event_acc.Reload()
print(event_acc.Tags())

{'images': [], 'audio': [], 'histograms': [], 'scalars': ['epoch_loss', 'epoch_accuracy'], 'distributions': [], 'tensors': ['testtesttest_1'], 'graph': False, 'meta_graph': False, 'run_metadata': []}


In [16]:
from tensorboard.backend.event_processing import event_accumulator
event_acc = event_accumulator.EventAccumulator('gs://'+os.environ['BUCKET_NAME']+'/training_model_gcp/tf_bert_classification_hp_tuning_cpu_2020_06_10_134028/tensorboard/trial_id_1/validation')
event_acc.Reload()
print(event_acc.Tags())

{'images': [], 'audio': [], 'histograms': [], 'scalars': ['epoch_accuracy', 'epoch_loss'], 'distributions': [], 'tensors': ['metric_accuracy_train_epoch', 'testtesttest_1'], 'graph': False, 'meta_graph': False, 'run_metadata': []}


In [17]:
from tensorboard.backend.event_processing import event_accumulator
event_acc = event_accumulator.EventAccumulator('gs://'+os.environ['BUCKET_NAME']+'/training_model_gcp/tf_bert_classification_hp_tuning_cpu_2020_06_10_134028/tensorboard/trial_id_1/train')
print(event_acc.Tags())

{'images': [], 'audio': [], 'histograms': [], 'scalars': [], 'distributions': [], 'tensors': [], 'graph': False, 'meta_graph': False, 'run_metadata': []}


In [ ]:
2020_06_10_113245

In [18]:
from tensorboard.backend.event_processing import event_accumulator
event_acc = event_accumulator.EventAccumulator('gs://'+os.environ['BUCKET_NAME']+'/training_model_gcp/tf_bert_classification_hp_tuning_cpu_2020_06_10_134028/tensorboard/trial_id_1/validation')
event_acc.Reload()
print(event_acc.Tags())

{'images': [], 'audio': [], 'histograms': [], 'scalars': ['epoch_accuracy', 'epoch_loss'], 'distributions': [], 'tensors': ['metric_accuracy_train_epoch', 'testtesttest_1'], 'graph': False, 'meta_graph': False, 'run_metadata': []}


In [19]:
for tag in sorted(event_acc.Tags()['tensors']):
    for scalar_event in event_acc.Tensors(tag):
        print('name: {} value: {} step: {}'.format(tag, tf.make_ndarray(scalar_event.tensor_proto), scalar_event.step))

name: metric_accuracy_train_epoch value: 0.5106981992721558 step: 0
name: testtesttest_1 value: 0.5106981992721558 step: 0


In [21]:
for tag in sorted(event_acc.Tags()['scalars']):
    print(tag)
    for scalar_event in event_acc.Scalars(tag):
        print(scalar_event.step, scalar_event.value)

epoch_accuracy
0 0.46875
epoch_loss
0 0.71041339635849
